### ISSUE TITLE
Unable to decompress workflow

### ISSUE THREAD

**Issue by ikravchenk0** [microsoft/Logic-App-STD-Advanced-Tools#3]
Hello,

Yesterday i accidentally removed all workflows in my Standard Logic App, and found this solution.
Done everything according to the instruction: uploaded executable into SCM, and executed the tool with **RestoreWorkflowWithVersion** option.
Executable of the latest version (at least at the time of this issue creation, 14.11.2024)
Logic app Stack config: .NET 8, 32 bit.

**Error**:

Restoring workflow DayforceGetIdDetails with ID a625e574bd2a4dd6851cfd919365d355 and version ID 08584701028214824072.
The type initializer for 'Microsoft.WindowsAzure.ResourceStack.Common.Compression.Internal.NativeMethods' threw an exception.
   at Microsoft.WindowsAzure.ResourceStack.Common.Compression.Internal.NativeMethods.ZStandard_decompress(Byte[] input, Int32 inputOffset, Int32 inputLength, Byte[] output, Int32 outputOffset, Int32 outputLength)
   at Microsoft.WindowsAzure.ResourceStack.Common.Compression.ModernCompressionUtility.InflateString(Byte[] input, Int32 offset, Int32 count, Int32 uncompressedLength, CompressionAlgorithm algorithm)
   at Microsoft.WindowsAzure.ResourceStack.Common.Compression.ModernCompressionUtility.InflateString(Stream input, Boolean leaveOpen)
   at LogicAppAdvancedTool.CommonOperations.DecompressContent(Byte[] content)
   at LogicAppAdvancedTool.CommonOperations.SaveDefinition(String path, String fileName, TableEntity entity)
   at LogicAppAdvancedTool.Operations.RestoreWorkflowWithVersion.Run(String workflowName)
   at LogicAppAdvancedTool.Program.<>c__DisplayClass0_25.<Main>b__78()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at LogicAppAdvancedTool.Program.Main(String[] args)

I also have tried **different executable version**, which was available yesterday, it seems that it was using different method for decompression (**deflate** i guess). There was an error too, but a bit different:

The archive entry was compressed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer)
   at System.IO.Compression.DeflateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.WindowsAzure.ResourceStack.Common.Extensions.StreamExtensions.BufferedCopyTo(Stream source, Stream destination, Int64 capacity)
   at Microsoft.WindowsAzure.ResourceStack.Common.Utilities.DeflateCompressionUtility.InflateStream(Stream input, Boolean leaveOpen)
   at Microsoft.WindowsAzure.ResourceStack.Common.Utilities.DeflateCompressionUtility.InflateString(Stream input, Boolean leaveOpen)
   at LogicAppAdvancedTool.CommonOperations.DecompressContent(Byte[] content)
   at LogicAppAdvancedTool.CommonOperations.SaveDefinition(String path, String fileName, TableEntity entity)
   at LogicAppAdvancedTool.Operations.RestoreWorkflowWithVersion.Run(String workflowName)
   at LogicAppAdvancedTool.Program.<>c__DisplayClass0_25.<Main>b__78()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at LogicAppAdvancedTool.Program.Main(String[] args)

Not sure how the Logic App compresses the data, which it places into Storage Table, not metinoned in documentations, at least i did not see it.
Maybe somebody knows what can be the problem here?

**Comment by Drac-Zhang** [comment]
Hi @ikravchenk0 
Yes, I found that the backend compress algorithm changed from deflate to zstd recently.
This is has been fixed in the latest release

**Comment by ikravchenk0** [comment]
Hello @Drac-Zhang ,
I can confirm, that using latest version from 15.11.2024 - everything works. 
Thanks a lot for help :)
